# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Android Build
      # You may pin to the exact commit or the version.
      # uses: vgaidarji/android-github-actions-build@0888eff41ad409a802aa4ccd7790a91891da9056
      uses: vgaidarji/android-github-actions-build@v1.0.1
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: lintDebug
      run: ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: test
      run: ./gradlew -Pci --console=plain :app:testDebug
